const KEY='detective_data_progress_v1';
const defaultState=()=>({story:[false,false,false,false,false],firstRun:true,ranks:[0,0,0,0,0],patterns:{},titles:[],caseNo:0,solved:0});
let state=load(), screen='home', mode=null, step=0, queue=[], qi=0, answered=false, current=null;
function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaultState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const steps=[
 {title:'散らばりの事件',short:'ドットプロット',icon:'●',intro:'6年1組のハンドボール投げの記録。去年より強くなったというウワサは本当か、散らばりから調べよう。',flavor:['学校の記録','町内運動会の記録','スポーツ大会の記録']},
 {title:'代表値の事件',short:'平均・中央値・最頻値',icon:'Ⅲ',intro:'商店街の靴屋さんから相談がきた。どのサイズを多く仕入れるべきか、3つの代表値を使い分けよう。',flavor:['靴屋の相談','給食の記録','図書館の貸出記録']},
 {title:'整理の事件',short:'度数分布表',icon:'▤',intro:'町の調査データが多すぎて読めない。階級に分け、度数分布表で手がかりを整理しよう。',flavor:['町の調査','健康調査','通学時間の調査']},
 {title:'山の形の事件',short:'ヒストグラム',icon:'▥',intro:'同じデータなのに、グラフの形がちがって見える。柱をすき間なく並べて分布の山を見つけよう。',flavor:['気温の記録','歩数の記録','読書時間の記録']},
 {title:'結論の事件',short:'読み解き・吟味',icon:'⌕',intro:'「この町の人はみんな運動が得意」と書かれた報告書。データの集め方や目盛りまで調べ、結論を吟味しよう。',flavor:['町の健康報告','アンケート結果','新聞のグラフ']}
];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function header(){return `<header class="top"><div class="brand"><div class="badge">⌕</div><div><h1>町のデータ探偵団</h1><small>データを見て、考えて、確かな結論を</small></div></div><div class="top-actions"><button class="btn" onclick="showNotebook()">探偵手帳</button><button class="btn ghost" onclick="goHome()">トップ</button></div></header>`}
function render(html){document.querySelector('#app').innerHTML=header()+html;window.scrollTo({top:0,behavior:'smooth'})}
function goHome(){screen='home';renderHome()}
function renderHome(){let done=state.story.filter(Boolean).length;render(`<section class="hero"><div class="eyebrow">CASE FILE 000　データ活用調査本部</div><h2>町のデータ探偵団</h2><p>町に届く「本当かな？」を、データという手がかりで解決しよう。ドットプロット、代表値、度数分布表、ヒストグラム、結論の吟味まで、5つの事件に挑戦します。</p><div class="top-actions"><button class="btn primary" onclick="startStory()">${done?'物語をつづける':'基本学習をはじめる'}</button><button class="btn gold" onclick="startPractice()">名探偵への道</button></div></section><div class="grid"><article class="card mode-card"><div><div class="mode-icon">📖</div><h3>基本学習モード</h3><p class="muted">5つの事件を順番に解決。初めて学ぶときは、こちらから。</p></div><span class="pill">${done}/5章クリア</span></article><article class="card mode-card"><div><div class="mode-icon">🕵️</div><h3>練習モード</h3><p class="muted">ランダム問題を何度でも。苦手パターンは優先して出題。</p></div><span class="pill gold">ランクアップ式</span></article></div><div class="section-title"><h2>5つの事件</h2><span class="muted">${done===5?'全事件解決！':'順番に解決しよう'}</span></div><div class="steps">${steps.map((s,i)=>`<article class="card step-card ${i>0&&!state.story[i-1]?'locked':''}"><div class="num">${s.icon} ${i+1}</div><h3>${s.short}</h3><span class="${state.story[i]?'pill':'muted'}">${state.story[i]?'解決済み':i>0&&!state.story[i-1]?'🔒 前の事件から':'挑戦できる'}</span></article>`).join('')}</div>`)}
function startStory(){let next=state.story.findIndex(x=>!x);step=next<0?0:next;mode='story';screen='chapters';renderChapters()}
function renderChapters(){render(`<div class="section-title"><h2>事件選択</h2><span class="muted">基本学習モード</span></div><div class="steps">${steps.map((s,i)=>{let open=i===0||state.story[i-1];return `<button class="card step-card ${!open?'locked':''}" ${open?`onclick="openStory(${i})"`:''}><div class="num">${s.icon} ${i+1}</div><h3>${s.title}</h3><span class="${state.story[i]?'pill':'muted'}">${state.story[i]?'解決済み':open?'調査開始':'🔒 前の事件を解決'}</span></button>`}).join('')}</div><div class="card" style="margin-top:18px"><h3>調査の進み具合</h3><div class="progress"><i style="width:${state.story.filter(Boolean).length*20}%"></i></div><p class="muted">${state.story.filter(Boolean).length}/5事件</p></div>`)}
function openStory(i){step=i;current=null;answered=false;renderStoryIntro()}
function renderStoryIntro(){let s=steps[step], revisit=state.story[step];render(`<section class="card" style="max-width:820px;margin:auto"><div class="eyebrow">第${step+1}章　${s.short}</div><h2>${s.title}</h2><div class="case-file"><b>依頼状</b><p>${s.intro}</p></div><p class="muted">${revisit?'この事件は解決済みです。':'この事件を解決すると手がかりカードを獲得できます。'}</p><button class="btn primary" onclick="beginStoryQuiz()">${revisit?'調査を再開する':'調査をはじめる'}</button></section>`)}
function beginStoryQuiz(){queue=makeQuestions(step,4);qi=0;mode='story';renderQuiz()}
function startPractice(s=0){mode='practice';step=s;queue=[];qi=0;nextPractice();}
function nextPractice(){state.caseNo++;save();current=makeQuestion(step);answered=false;renderQuiz()}
function renderQuiz(){let q=current||queue[qi];current=q;let s=steps[step], total=mode==='story'?queue.length:1;let fl=s.flavor[Math.floor(Math.random()*s.flavor.length)];render(`<section class="card question"><div class="q-head"><span class="q-number">${mode==='story'?`第${step+1}章　${qi+1}/${total}`:`事件ファイル No.${String(state.caseNo).padStart(3,'0')}`}</span><span class="pill">${s.short}</span></div>${mode==='practice'?`<div class="case-file"><b>${fl}</b>から届いた未解決事件。データを手がかりに調査しよう。</div>`:''}<h2 class="q-title">${q.text}</h2>${q.visual||''}<div class="choices">${q.choices.map((c,i)=>`<button class="choice" id="choice${i}" onclick="answer(${i})">${esc(c)}</button>`).join('')}</div><div id="feedback"></div></section>`)}
function answer(i){if(answered)return;answered=true;let q=current,ok=i===q.answer,rankUp='';document.querySelectorAll('.choice').forEach((b,n)=>{if(n===q.answer)b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});if(mode==='practice'&&ok){let before=rankName(state.ranks[step]);state.ranks[step]++;state.solved++;let after=rankName(state.ranks[step]);if(before!==after)rankUp=`<div class="rank-up">🎉 ${after}に昇格！<br><small>先輩探偵「その調子で、データの見方をみがこう！」</small></div>`;save()}let box=document.querySelector('#feedback');box.className='feedback '+(ok?'ok':'bad');box.innerHTML=`<b>${ok?'正解！':'もう一度、手がかりを見直そう。'}</b>${rankUp}<p>${q.explain}</p><button class="btn ${ok?'primary':'ghost'}" onclick="afterAnswer(${ok})">${mode==='story'?(qi<queue.length-1?'次の問題へ':'章末ミニ問題へ'):'次の事件を調べる'}</button>`;record(q.pattern,ok)}
function afterAnswer(ok){if(mode==='story'){if(qi<queue.length-1){qi++;answered=false;current=null;renderQuiz()}else renderMini()}else nextPractice()}
function record(pattern,ok){let key=pattern.startsWith('s')?pattern:`s${step+1}-${pattern}`,p=state.patterns[key]||{wrong:0,right:0,weak:false};if(ok){p.right++;p.wrong=0;if(p.right>=2)p.weak=false}else{p.wrong++;p.right=0;if(p.wrong>=3)p.weak=true}state.patterns[key]=p;save()}
function makeQuestions(s,n){return Array.from({length:n},()=>makeQuestion(s))}
function makeQuestion(s){let weak=Object.entries(state.patterns).filter(([id,p])=>p.weak&&id.startsWith('s'+(s+1)+'-'));if(weak.length&&Math.random()<.65){let id=weak[Math.floor(Math.random()*weak.length)][0];return makeQuestionByPattern(s,id)}return [qDot,qRep,qFreq,qHist,qCrit][s]({patternPrefix:'s'+(s+1)+'-'})}
function makeQuestionByPattern(s,id){return [qDot,qRep,qFreq,qHist,qCrit][s]({pattern:id.slice(3)})}
function dotData(){let base=Array.from({length:7},(_,i)=>i+3),data=[];base.forEach(v=>{for(let j=0;j<Math.floor(Math.random()*4)+(v===6?2:0);j++)data.push(v)});return data.sort((a,b)=>a-b)}
function dotVisual(data){let min=Math.min(...data),max=Math.max(...data);return `<div class="chart"><div class="dotplot">${Array.from({length:max-min+1},(_,j)=>{let v=min+j,c=data.filter(x=>x===v).length;return `<div class="dot-col">${Array.from({length:c},()=>'<i class="dot"></i>').join('')}<span class="dot-label">${v}</span></div>`}).join('')}</div></div>`}
function qDot(){let d=dotData(),min=Math.min(...d),max=Math.max(...d);let type=Math.random()<.5?'range':'max';return {pattern:'dot-'+type,text:`このドットプロットの${type==='range'?'範囲（最大値−最小値）':'最大値'}はいくつですか。`,visual:dotVisual(d),choices:type==='range'?[String(max-min),String(max+min),String(d.length),String(max-min+1)]:[String(max),String(min),String(max-min),String(d.length)],answer:0,explain:type==='range'?`最大値${max}から最小値${min}をひいて、${max}-${min}=${max-min}です。`:`いちばん右の点が最大値です。${max}でした。`}}
function qRep(){let n=Math.random()<.5?5:6,d=Array.from({length:n},()=>Math.floor(Math.random()*5)+3);d[0]=6;d[1]=6;d.sort((a,b)=>a-b);let sum=d.reduce((a,b)=>a+b,0),med=n%2?d[(n-1)/2]:(d[n/2-1]+d[n/2])/2,type=Math.floor(Math.random()*3),names=['平均値','中央値','最頻値'],pattern=['mean','median','mode'][type],ans=type===0?sum/n:type===1?med:6;let distractors=[sum,d[0],d[n-1],ans+1,ans-1].filter(x=>x!==ans&&x>=0),choices=[ans,...distractors].map(String).slice(0,4);return {pattern:'rep-'+pattern,text:`データ ${d.join('、')} の${names[type]}はいくつですか。`,choices,answer:0,explain:type===0?`合計${sum}を個数${n}で割ります。${sum}÷${n}=${ans}です。`:type===1?`大きさ順に並べたときの中央は、${n%2?'中央の1つ':'中央2つ'}です。中央値は${ans}です。`:'最も多く現れる値を見ます。6が2回現れているので、最頻値は6です。'}}
function qFreq(){let a=3+Math.floor(Math.random()*4), b=a+5, data=Array.from({length:12},()=>Math.floor(Math.random()*20)+1),mid=data.filter(x=>x>=a&&x<b).length;return {pattern:'freq-class',text:`階級「${a}以上${b}未満」に入るデータの度数はいくつですか。`,visual:`<table class="table"><tr><th>データ</th></tr><tr><td>${data.sort((x,y)=>x-y).join('、')}</td></tr></table>`,choices:[String(mid),String(data.length-mid),String(b-a),String(a+b)],answer:0,explain:`${a}以上${b}未満の値だけを数えると${mid}個です。${b}は含まないことに注意します。`}}
function histData(){let counts=Array.from({length:5},()=>Math.floor(Math.random()*8)+2);return counts}
function histVisual(c){return `<div class="chart"><div class="bars">${c.map((v,i)=>`<div class="bar-col"><b style="height:${v*16}px"></b><span>${i*10+0}〜${i*10+9}</span></div>`).join('')}</div></div>`}
function qHist(){let c=histData(),max=Math.max(...c),idx=c.indexOf(max);return {pattern:'hist-peak',text:'このヒストグラムで、最も度数が多い階級はどれですか。',visual:histVisual(c),choices:c.map((_,i)=>`${i*10}〜${i*10+9}`),answer:idx,explain:`いちばん高い柱は${idx*10}〜${idx*10+9}の階級です。山の頂上に注目します。`}}
function qCrit(){let kind=Math.random()<.5?'sample':'scale';return kind==='sample'?{pattern:'crit-sample',text:'「町全体の人は、みんな毎日1時間運動する」と結論づけました。調査対象がクラスの友達10人だけなら、どう考えるのが妥当ですか。',choices:['町全体と決めつけるには、調査対象がかたよっている可能性がある','10人調べたので必ず正しい','平均値だけ見れば十分','データは使わない'],answer:0,explain:'調査対象の人数や選び方を確認し、町全体について言えるかを慎重に考えます。'}:{pattern:'crit-scale',text:'グラフの変化を実際より大きく見せないために、まず何を確認しますか。',choices:['目盛りの間隔や省略がないか','柱の色だけ','タイトルの長さ','データを見ない'],answer:0,explain:'目盛りの幅や省略線によって印象が変わることがあります。'}}
function renderMini(){let q=qCrit(),s=steps[step];render(`<section class="card question"><div class="eyebrow">章末ミニ問題</div><h2 class="q-title">${q.text}</h2><div class="choices">${q.choices.map((c,i)=>`<button class="choice" onclick="miniAnswer(${i},${q.answer},'${esc(q.explain)}')">${esc(c)}</button>`).join('')}</div><div id="feedback"></div></section>`)}
function miniAnswer(i,a,e){let ok=i===a;document.querySelectorAll('.choice').forEach((b,n)=>{if(n===a)b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});let f=document.querySelector('#feedback');f.className='feedback '+(ok?'ok':'bad');f.innerHTML=`<b>${ok?'正解！':'考え方を確認しよう。'}</b><p>${e}</p><button class="btn primary" onclick="finishStory()">事件解決へ</button>`}
function finishStory(){state.story[step]=true;state.firstRun=false;save();render(`<section class="result-card card"><div style="font-size:4rem">🗂️</div><div class="eyebrow">事件解決</div><h2>${steps[step].title}を解決！</h2><p>手がかりカード「${steps[step].short}」を探偵手帳に保存しました。</p><button class="btn primary" onclick="${step<4?'openStory('+(step+1)+')':'goHome()'}">${step<4?'次の事件へ':'事件選択へ'}</button></section>`)}
function rankName(n){return n>=200?'伝説の探偵':n>=100?'名探偵':n>=50?'ベテラン探偵':n>=20?'一人前探偵':'見習い探偵'}
function showNotebook(){render(`<div class="section-title"><h2>探偵手帳</h2><span class="muted">調査の記録</span></div><div class="grid">${steps.map((s,i)=>{let n=state.ranks[i]||0;return `<article class="card"><div class="bar"><b>Step ${i+1}　${s.short}</b><span class="rank">${rankName(n)}</span></div><p class="muted">累積正解 ${n}問　／　解決済み事件 ${n}件</p><div class="progress"><i style="width:${Math.min(100,n/2)}%"></i></div><button class="btn primary" style="margin-top:12px" onclick="startPractice(${i})">この章を特訓</button></article>`}).join('')}</div><section class="card" style="margin-top:18px"><h3>未解決事件（にがてパターン）</h3><div class="note-list">${Object.entries(state.patterns).filter(([,p])=>p.weak).map(([id,p])=>`<div class="weak"><span><b>${patternLabel(id)}</b><br><small>連続${p.wrong}回不正解</small></span><button class="btn" onclick="startPractice(${Number(id[1])-1})">特訓</button></div>`).join('')||'<div class="empty">まだ未解決事件はありません。間違いも大切な手がかりです。</div>'}</div></section><section class="card" style="margin-top:18px"><h3>称号</h3><p>${state.ranks.every(n=>n>=200)?'<span class="pill gold">殿堂入り探偵</span>':'5つの章すべてで伝説の探偵を目指そう。'}</p></section>`)}
function patternLabel(id){return ({'s1-dot-range':'ドットプロット：範囲','s1-dot-max':'ドットプロット：最大値','s2-rep-mean':'平均値','s2-rep-median':'中央値','s2-rep-mode':'最頻値','s3-freq-class':'度数分布表：階級','s4-hist-peak':'ヒストグラム：山の頂上','s5-crit-sample':'結論：調査対象','s5-crit-scale':'結論：目盛り'})[id]||id}
renderHome();
